export type ReleaseState =
  | "PLANNED"
  | "READY"
  | "PRECHECK"
  | "CANARY"
  | "OBSERVING"
  | "PROMOTION_PENDING"
  | "PROMOTING"
  | "HOLD"
  | "PAUSED"
  | "ROLLBACK_PENDING"
  | "ROLLING_BACK"
  | "RECOVERY_VERIFY"
  | "PROMOTED"
  | "ROLLED_BACK"
  | "FAILED"
  | "ABORTED";

export const VALID_RELEASE_TRANSITIONS: Record<ReleaseState, ReleaseState[]> = {
  PLANNED: ["READY", "ABORTED", "HOLD"],
  READY: ["PRECHECK", "ABORTED", "HOLD"],
  PRECHECK: ["CANARY", "HOLD", "PAUSED", "ABORTED"],
  CANARY: ["OBSERVING", "PAUSED", "ROLLBACK_PENDING", "ABORTED"],
  OBSERVING: ["PROMOTION_PENDING", "HOLD", "PAUSED", "ROLLBACK_PENDING", "ABORTED"],
  PROMOTION_PENDING: ["PROMOTING", "HOLD", "PAUSED", "ROLLBACK_PENDING"],
  PROMOTING: ["OBSERVING", "ROLLBACK_PENDING", "ABORTED"],
  HOLD: ["OBSERVING", "PAUSED", "ABORTED", "ROLLBACK_PENDING"],
  PAUSED: ["OBSERVING", "ABORTED", "ROLLBACK_PENDING"],
  ROLLBACK_PENDING: ["ROLLING_BACK", "ABORTED"],
  ROLLING_BACK: ["RECOVERY_VERIFY", "FAILED"],
  RECOVERY_VERIFY: ["ROLLED_BACK", "FAILED"],
  PROMOTED: [],
  ROLLED_BACK: [],
  FAILED: [],
  ABORTED: [],
};

export class WorkerReleaseState {
  transition(from: ReleaseState, to: ReleaseState): boolean {
    return VALID_RELEASE_TRANSITIONS[from]?.includes(to) ?? false;
  }
}
