// scripts/verify-phase208-evidence.ts
// Phase 209: independent verification of the legacy Phase 208 evidence
// artifact that was committed before the Phase 209 integrity model existed.
//
// The legacy artifact was generated by a script that hard-coded counts and
// wrote no digest. It therefore cannot be independently verified and MUST
// be reported as UNVERIFIED. This command does NOT retroactively stamp it.
//
// Exit: 0=VERIFIED_PASS  1=TAMPERED/FAIL  2=BLOCKED  3=UNVERIFIED

import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { verifyStoredEvidence } from "../src/core/verification-evidence";

function main(): void {
  const path = resolve("artifacts/phase208/phase208-evidence.json");
  if (!existsSync(path)) {
    console.error("phase208 evidence not found at " + path);
    process.exit(2);
  }
  const raw = JSON.parse(readFileSync(path, "utf8"));
  const check = verifyStoredEvidence(raw);

  console.log("===== Phase 208 legacy evidence verification =====");
  console.log("file:", path);
  console.log("verdict:", check.verdict);
  console.log("reasons:", check.reasons.join(" | ") || "(none)");
  console.log("provided resultDigest:", check.providedResultDigest);
  console.log("recomputed resultDigest:", check.recomputedResultDigest);
  console.log("provided evidenceDigest:", check.providedEvidenceDigest);
  console.log("recomputed evidenceDigest:", check.recomputedEvidenceDigest);

  if (check.verdict === "VERIFIED_PASS") process.exit(0);
  if (check.verdict === "TAMPERED" || check.verdict === "VERIFIED_FAIL") process.exit(1);
  if (check.verdict === "VERIFIED_BLOCKED") process.exit(2);
  process.exit(3);
}

main();
